name: Build CachyOS Kernel with Patches

on:
  workflow_dispatch:
    inputs:
      kernel:
        description: '选择编译的内核'
        required: true
        default: 'linux-cachyos-bore'
        type: choice
        options:
          - linux-cachyos
          - linux-cachyos-bore
          - linux-cachyos-bmq
          - linux-cachyos-deckify
          - linux-cachyos-eevdf
          - linux-cachyos-lts
          - linux-cachyos-server
          - linux-cachyos-hardened
          - linux-cachyos-rc
          - linux-cachyos-rt-bore

      compiler:
        description: '选择编译器'
        required: true
        default: 'llvm'
        type: choice
        options:
          - llvm
          - gcc

jobs:
  build-kernels:
    name: Build Kernels
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v7
        with:
          fetch-depth: '0'

      - name: Install Docker
        uses: docker/setup-docker-action@v5

      - name: Clone linux-cachyos repository
        run: |
          git clone https://github.com/CachyOS/linux-cachyos.git
          cd linux-cachyos
          git checkout "master"
          echo "Checked out branch/tag: master"
          git log --oneline -n 3
          # 只保留我需要的分支内核
          find . -maxdepth 1 -type d ! -name "." ! -name "${{ inputs.kernel }}" -exec rm -rf {} +

      - name: Copy patches
        run: |
          cd linux-cachyos

          # 检查 patch 目录是否存在
          if [ ! -d "../patch" ]; then
            echo "::error::patch/ directory not found in the repository root!"
            exit 1
          fi

          echo "=== Available patches ==="
          ls -la ../patch/

          echo ""
          echo "=== Kernel directories found,copy patch ==="
          for dir in linux-cachy*/; do
            echo "  - $dir"
            cp -r ../patch/* $dir/
          done

      - name: Build docker
        run: |
          time docker build -t local/docker-makepkg-v4 ./makepkg-v4

      - name: Start compiling
        run: |
          cd linux-cachyos
          sudo chown -R $USER:$USER .
          ## 1. 全局配置修改
          ## zfs
          # find . -name "PKGBUILD" | xargs -I {} sed -i "s/_build_zfs:=no/_build_zfs:=yes/" {}
          ## v4架构
          find . -name "PKGBUILD" | xargs -I {} sed -i "s/_processor_opt:=/_processor_opt:=GENERIC_V4/" {}
          find . -name "PKGBUILD" | xargs -I {} sed -i "s/_use_auto_optimization:=yes/_use_auto_optimization:=no/" {}
          ## N卡
          # find . -name "PKGBUILD" | xargs -I {} sed -i "s/_build_nvidia_open:=no/_build_nvidia_open:=yes/" {}
          ## r8125
          # find . -name "PKGBUILD" | xargs -I {} sed -i "s/_build_r8125:=no/_build_r8125:=yes/" {}
          ## bbr3
          find . -name "PKGBUILD" | xargs -I {} sed -i "s/_tcp_bbr3:=no/_tcp_bbr3:=yes/" {}
          ## 默认性能（有问题，不管开不开cpu都锁在5w）
          find . -name "PKGBUILD" | xargs -I {} sed -i "s/_per_gov:=no/_per_gov:=yes/" {}

          echo "当前选择的内核: ${{ inputs.kernel }}"
          echo "当前选择的编译器: ${{ inputs.compiler }}"
          
          ## gcc内核不用lto
          find . -name "PKGBUILD" | xargs -I {} sed -i "s/_use_llvm_lto:=thin/_use_llvm_lto:=none/" {}
          
          if [ "${{ inputs.compiler }}" == "gcc" ]; then
            echo "🔨 正在使用 GCC (无 LTO) 编译..."

            files=$(find . -name "PKGBUILD")
            for f in $files
            do
                d=$(dirname $f)
                cd $d
                time docker run --name kernelbuild -e EXPORT_PKG=1 -e SYNC_DATABASE=1 -e CHECKSUMS=1 -v $PWD:/pkg local/docker-makepkg-v4
                docker rm kernelbuild
                cd ..
            done

          elif [ "${{ inputs.compiler }}" == "llvm" ]; then
            echo "🔨 正在使用 LLVM ThinLTO 编译..."

            find . -name "PKGBUILD" | xargs -I {} sed -i "s/_use_llvm_lto:=none/_use_llvm_lto:=thin/" {}
            
            files=$(find . -name "PKGBUILD")
            for f in $files
            do
                d=$(dirname $f)
                cd $d
                time docker run --name kernelbuild -e EXPORT_PKG=1 -e SYNC_DATABASE=1 -e CHECKSUMS=1 -v $PWD:/pkg local/docker-makepkg-v4
                docker rm kernelbuild
                cd ..
            done
          fi

          mkdir -p local
          mv */*.pkg.tar.zst* local/ || echo "Warning: No packages found to move."
          echo "Local repository updated successfully!"

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: cachyos-kernel-build-artifacts
          path: |
            linux-cachyos/local/*.pkg.tar.zst
          retention-days: 7
